// harness/templates.ts — Real code templates for React Native / Flutter / Website
// Used by harnessRun.ts builderWriteFiles to generate actual app code per framework

const RN_LOGIN_SCREEN = `// LoginScreen.tsx — Generated by Caide
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native';

export default function LoginScreen() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = () => {
    setLoading(true);
    setTimeout(() => { setLoading(false); setError('Invalid credentials'); }, 2000);
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Login</Text>
      {error ? <Text style={styles.error}>{error}</Text> : null}
      <TextInput style={styles.input} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize="none" />
      <TextInput style={styles.input} placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry />
      <TouchableOpacity style={styles.button} onPress={handleLogin} disabled={loading}>
        {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Sign In</Text>}
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: '#0D0D0D' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 24, textAlign: 'center' },
  input: { height: 48, borderColor: '#333', borderWidth: 1, borderRadius: 12, paddingHorizontal: 16, color: '#fff', backgroundColor: '#1a1a1a', marginBottom: 12 },
  button: { height: 48, backgroundColor: '#fff', borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginTop: 8 },
  buttonText: { color: '#000', fontWeight: '600' },
  error: { color: '#E8493C', fontSize: 12, marginBottom: 8, textAlign: 'center' },
});`;

const WEBSITE_LOGIN = `// src/Login.tsx — Generated by Caide
import { useState } from 'react';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async () => {
    setLoading(true);
    setError('');
    try {
      // POST to your API
      await fetch('/api/login', { method: 'POST', body: JSON.stringify({ email, password }) });
    } catch { setError('Login failed'); }
    finally { setLoading(false); }
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0D0D0D' }}>
      <div style={{ width: 360, padding: 32, borderRadius: 20, border: '1px solid #333', background: '#111' }}>
        <h2 style={{ color: '#fff', fontSize: 24, fontWeight: 'bold', textAlign: 'center', marginBottom: 24 }}>Login</h2>
        {error && <p style={{ color: '#E8493C', fontSize: 12, textAlign: 'center', marginBottom: 8 }}>{error}</p>}
        <input style={{ width: '100%', height: 48, border: '1px solid #333', borderRadius: 12, padding: '0 16px', color: '#fff', background: '#1a1a1a', marginBottom: 12, fontSize: 14 }} placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} />
        <input style={{ width: '100%', height: 48, border: '1px solid #333', borderRadius: 12, padding: '0 16px', color: '#fff', background: '#1a1a1a', marginBottom: 12, fontSize: 14 }} type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />
        <button onClick={handleLogin} disabled={loading} style={{ width: '100%', height: 48, background: '#fff', borderRadius: 24, border: 'none', fontWeight: '600', cursor: 'pointer', marginTop: 8 }}>{loading ? 'Signing in...' : 'Sign In'}</button>
      </div>
    </div>
  );
}`;

const FLUTTER_LOGIN = `// lib/login_screen.dart — Generated by Caide
import 'package:flutter/material.dart';

class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  bool _loading = false;
  String? _error;

  void _login() {
    setState(() => _loading = true);
    Future.delayed(Duration(seconds: 2), () {
      setState(() { _loading = false; _error = 'Invalid credentials'; });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF0D0D0D),
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Login', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white)),
              if (_error != null) Padding(
                padding: EdgeInsets.only(top: 8),
                child: Text(_error!, style: TextStyle(color: Color(0xFFE8493C), fontSize: 12)),
              ),
              SizedBox(height: 24),
              TextField(controller: _emailController, decoration: InputDecoration(hintText: 'Email', filled: true, fillColor: Color(0xFF1A1A1A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Color(0xFF333)))), style: TextStyle(color: Colors.white)),
              SizedBox(height: 12),
              TextField(controller: _passwordController, obscureText: true, decoration: InputDecoration(hintText: 'Password', filled: true, fillColor: Color(0xFF1A1A1A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Color(0xFF333)))), style: TextStyle(color: Colors.white)),
              SizedBox(height: 16),
              ElevatedButton(
                onPressed: _loading ? null : _login,
                style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: Colors.black, shape: StadiumBorder(), minimumSize: Size(double.infinity, 48)),
                child: _loading ? CircularProgressIndicator(color: Colors.black) : Text('Sign In', style: TextStyle(fontWeight: FontWeight.w600)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}`;

export const TEMPLATES: Record<string, Record<string, string>> = {
  "react-native": { "LoginScreen": RN_LOGIN_SCREEN },
  "website": { "Login": WEBSITE_LOGIN },
  "flutter": { "login_screen.dart": FLUTTER_LOGIN },
  "blank": {},
};

export function getTemplate(framework: string, fileName: string): string | undefined {
  return TEMPLATES[framework]?.[fileName];
}
