// harness/templates.ts — Real code templates for React Native / Flutter / Website
// Used by harnessRun.ts builderWriteFiles to generate actual app code per framework

const RN_LOGIN_SCREEN = `// LoginScreen.tsx — Generated by Caide
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native';

export default function LoginScreen() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = () => {
    setLoading(true);
    setTimeout(() => { setLoading(false); setError('Invalid credentials'); }, 2000);
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Login</Text>
      {error ? <Text style={styles.error}>{error}</Text> : null}
      <TextInput style={styles.input} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize="none" />
      <TextInput style={styles.input} placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry />
      <TouchableOpacity style={styles.button} onPress={handleLogin} disabled={loading}>
        {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Sign In</Text>}
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: '#0D0D0D' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 24, textAlign: 'center' },
  input: { height: 48, borderColor: '#333', borderWidth: 1, borderRadius: 12, paddingHorizontal: 16, color: '#fff', backgroundColor: '#1a1a1a', marginBottom: 12 },
  button: { height: 48, backgroundColor: '#fff', borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginTop: 8 },
  buttonText: { color: '#000', fontWeight: '600' },
  error: { color: '#E8493C', fontSize: 12, marginBottom: 8, textAlign: 'center' },
});`;

const WEBSITE_LOGIN = `// src/Login.tsx — Generated by Caide
import { useState } from 'react';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async () => {
    setLoading(true);
    setError('');
    try {
      await fetch('/api/login', { method: 'POST', body: JSON.stringify({ email, password }) });
    } catch { setError('Login failed'); }
    finally { setLoading(false); }
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0D0D0D' }}>
      <div style={{ width: 360, padding: 32, borderRadius: 20, border: '1px solid #333', background: '#111' }}>
        <h2 style={{ color: '#fff', fontSize: 24, fontWeight: 'bold', textAlign: 'center', marginBottom: 24 }}>Login</h2>
        {error && <p style={{ color: '#E8493C', fontSize: 12, textAlign: 'center', marginBottom: 8 }}>{error}</p>}
        <input style={{ width: '100%', height: 48, border: '1px solid #333', borderRadius: 12, padding: '0 16px', color: '#fff', background: '#1a1a1a', marginBottom: 12, fontSize: 14 }} placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} />
        <input style={{ width: '100%', height: 48, border: '1px solid #333', borderRadius: 12, padding: '0 16px', color: '#fff', background: '#1a1a1a', marginBottom: 12, fontSize: 14 }} type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />
        <button onClick={handleLogin} disabled={loading} style={{ width: '100%', height: 48, background: '#fff', borderRadius: 24, border: 'none', fontWeight: '600', cursor: 'pointer', marginTop: 8 }}>{loading ? 'Signing in...' : 'Sign In'}</button>
      </div>
    </div>
  );
}`;

const FLUTTER_LOGIN = `// lib/login_screen.dart — Generated by Caide
import 'package:flutter/material.dart';

class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  bool _loading = false;
  String? _error;

  void _login() {
    setState(() => _loading = true);
    Future.delayed(Duration(seconds: 2), () {
      setState(() { _loading = false; _error = 'Invalid credentials'; });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF0D0D0D),
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Login', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white)),
              if (_error != null) Padding(
                padding: EdgeInsets.only(top: 8),
                child: Text(_error!, style: TextStyle(color: Color(0xFFE8493C), fontSize: 12)),
              ),
              SizedBox(height: 24),
              TextField(controller: _emailController, decoration: InputDecoration(hintText: 'Email', filled: true, fillColor: Color(0xFF1A1A1A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Color(0xFF333)))), style: TextStyle(color: Colors.white)),
              SizedBox(height: 12),
              TextField(controller: _passwordController, obscureText: true, decoration: InputDecoration(hintText: 'Password', filled: true, fillColor: Color(0xFF1A1A1A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Color(0xFF333)))), style: TextStyle(color: Colors.white)),
              SizedBox(height: 16),
              ElevatedButton(
                onPressed: _loading ? null : _login,
                style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: Colors.black, shape: StadiumBorder(), minimumSize: Size(double.infinity, 48)),
                child: _loading ? CircularProgressIndicator(color: Colors.black) : Text('Sign In', style: TextStyle(fontWeight: FontWeight.w600)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}`;

const RN_HOME_SCREEN = `// HomeScreen.tsx — Generated by Caide
import React from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet } from 'react-native';

const DATA = [
  { id: '1', title: 'Item One', subtitle: 'Description one' },
  { id: '2', title: 'Item Two', subtitle: 'Description two' },
  { id: '3', title: 'Item Three', subtitle: 'Description three' },
];

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Home</Text>
      <FlatList data={DATA} keyExtractor={item => item.id} renderItem={({ item }) => (
        <TouchableOpacity style={styles.item}>
          <Text style={styles.itemTitle}>{item.title}</Text>
          <Text style={styles.itemSubtitle}>{item.subtitle}</Text>
        </TouchableOpacity>
      )} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0D0D0D', padding: 16 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 16 },
  item: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#333' },
  itemTitle: { fontSize: 16, fontWeight: '600', color: '#fff' },
  itemSubtitle: { fontSize: 12, color: '#999', marginTop: 4 },
});`;

const RN_SETTINGS_SCREEN = `// SettingsScreen.tsx — Generated by Caide
import React, { useState } from 'react';
import { View, Text, Switch, TouchableOpacity, StyleSheet } from 'react-native';

export default function SettingsScreen() {
  const [darkMode, setDarkMode] = useState(true);
  const [notifications, setNotifications] = useState(true);

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Settings</Text>
      <View style={styles.row}>
        <Text style={styles.label}>Dark Mode</Text>
        <Switch value={darkMode} onValueChange={setDarkMode} trackColor={{ false: '#333', true: '#E8493C' }} />
      </View>
      <View style={styles.row}>
        <Text style={styles.label}>Notifications</Text>
        <Switch value={notifications} onValueChange={setNotifications} trackColor={{ false: '#333', true: '#E8493C' }} />
      </View>
      <TouchableOpacity style={styles.button}>
        <Text style={styles.buttonText}>Sign Out</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0D0D0D', padding: 16 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 24 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#333' },
  label: { fontSize: 16, color: '#fff' },
  button: { marginTop: 24, height: 48, backgroundColor: '#333', borderRadius: 24, justifyContent: 'center', alignItems: 'center' },
  buttonText: { color: '#E8493C', fontWeight: '600' },
});`;

const WEBSITE_HOME = `// src/Home.tsx — Generated by Caide
import { useState } from 'react';

const DATA = [
  { id: '1', title: 'Item One', subtitle: 'Description one' },
  { id: '2', title: 'Item Two', subtitle: 'Description two' },
  { id: '3', title: 'Item Three', subtitle: 'Description three' },
];

export default function Home() {
  return (
    <div style={{ minHeight: '100vh', background: '#0D0D0D', padding: 24 }}>
      <h1 style={{ color: '#fff', fontSize: 24, fontWeight: 'bold', marginBottom: 16 }}>Home</h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {DATA.map(item => (
          <div key={item.id} style={{ padding: 16, borderRadius: 12, border: '1px solid #333', background: '#111' }}>
            <h3 style={{ color: '#fff', fontSize: 16, fontWeight: 600, margin: 0 }}>{item.title}</h3>
            <p style={{ color: '#999', fontSize: 12, margin: '4px 0 0' }}>{item.subtitle}</p>
          </div>
        ))}
      </div>
    </div>
  );
}`;

const WEBSITE_SETTINGS = `// src/Settings.tsx — Generated by Caide
import { useState } from 'react';

export default function Settings() {
  const [darkMode, setDarkMode] = useState(true);
  const [notifications, setNotifications] = useState(true);

  return (
    <div style={{ minHeight: '100vh', background: '#0D0D0D', padding: 24 }}>
      <h1 style={{ color: '#fff', fontSize: 24, fontWeight: 'bold', marginBottom: 24 }}>Settings</h1>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 12, borderRadius: 12, border: '1px solid #333', background: '#111' }}>
          <span style={{ color: '#fff', fontSize: 14 }}>Dark Mode</span>
          <input type="checkbox" checked={darkMode} onChange={e => setDarkMode(e.target.checked)} style={{ accentColor: '#E8493C' }} />
        </label>
        <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 12, borderRadius: 12, border: '1px solid #333', background: '#111' }}>
          <span style={{ color: '#fff', fontSize: 14 }}>Notifications</span>
          <input type="checkbox" checked={notifications} onChange={e => setNotifications(e.target.checked)} style={{ accentColor: '#E8493C' }} />
        </label>
        <button style={{ marginTop: 12, height: 48, background: '#333', borderRadius: 24, border: 'none', color: '#E8493C', fontWeight: 600, cursor: 'pointer' }}>Sign Out</button>
      </div>
    </div>
  );
}`;

const FLUTTER_HOME = `// lib/home_screen.dart — Generated by Caide
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  final List<Map<String, String>> items = [
    {'title': 'Item One', 'subtitle': 'Description one'},
    {'title': 'Item Two', 'subtitle': 'Description two'},
    {'title': 'Item Three', 'subtitle': 'Description three'},
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF0D0D0D),
      appBar: AppBar(title: Text('Home', style: TextStyle(color: Colors.white)), backgroundColor: Colors.transparent, elevation: 0),
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) => ListTile(
          title: Text(items[index]['title']!, style: TextStyle(color: Colors.white)),
          subtitle: Text(items[index]['subtitle']!, style: TextStyle(color: Colors.grey)),
          tileColor: Color(0xFF111111),
        ),
      ),
    );
  }
}`;

const FLUTTER_SETTINGS = `// lib/settings_screen.dart — Generated by Caide
import 'package:flutter/material.dart';

class SettingsScreen extends StatefulWidget {
  @override
  _SettingsScreenState createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  bool darkMode = true;
  bool notifications = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF0D0D0D),
      appBar: AppBar(title: Text('Settings', style: TextStyle(color: Colors.white)), backgroundColor: Colors.transparent, elevation: 0),
      body: ListView(
        children: [
          SwitchListTile(title: Text('Dark Mode', style: TextStyle(color: Colors.white)), value: darkMode, onChanged: (v) => setState(() => darkMode = v), activeColor: Color(0xFFE8493C)),
          SwitchListTile(title: Text('Notifications', style: TextStyle(color: Colors.white)), value: notifications, onChanged: (v) => setState(() => notifications = v), activeColor: Color(0xFFE8493C)),
          Padding(
            padding: EdgeInsets.all(16),
            child: ElevatedButton(
              onPressed: () {},
              style: ElevatedButton.styleFrom(backgroundColor: Color(0xFF333333), foregroundColor: Color(0xFFE8493C), shape: StadiumBorder(), minimumSize: Size(double.infinity, 48)),
              child: Text('Sign Out', style: TextStyle(fontWeight: FontWeight.w600)),
            ),
          ),
        ],
      ),
    );
  }
}`;

export const TEMPLATES: Record<string, Record<string, string>> = {
  "react-native": {
    "LoginScreen": RN_LOGIN_SCREEN,
    "HomeScreen": RN_HOME_SCREEN,
    "SettingsScreen": RN_SETTINGS_SCREEN,
  },
  "website": {
    "Login": WEBSITE_LOGIN,
    "Home": WEBSITE_HOME,
    "Settings": WEBSITE_SETTINGS,
  },
  "flutter": {
    "login_screen.dart": FLUTTER_LOGIN,
    "home_screen.dart": FLUTTER_HOME,
    "settings_screen.dart": FLUTTER_SETTINGS,
  },
  "blank": {},
};

export function getTemplate(framework: string, fileName: string): string | undefined {
  return TEMPLATES[framework]?.[fileName];
}

// M7: Match spec keywords to template names
export function matchTemplate(spec: string, framework: string): string | undefined {
  const lower = spec.toLowerCase();
  if (lower.includes("login") || lower.includes("sign in")) return getTemplate(framework, framework === "flutter" ? "login_screen.dart" : "LoginScreen");
  if (lower.includes("home") || lower.includes("dashboard") || lower.includes("list") || lower.includes("browse")) return getTemplate(framework, framework === "flutter" ? "home_screen.dart" : "HomeScreen");
  if (lower.includes("settings") || lower.includes("profile") || lower.includes("preferences")) return getTemplate(framework, framework === "flutter" ? "settings_screen.dart" : "SettingsScreen");
  return undefined;
}
