// Generates src/raw-assets/index.ts from every `?raw` import in the engine.
// Rolldown/tsdown resolves `?raw` nondeterministically (flaky "Could not
// load … No such file or directory" for files that exist), so raw text
// assets are instead compiled into a plain TS module at build prep time.
// Usage: bun scripts/generate-raw-assets.ts

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, relative, resolve, dirname } from "node:path";

const ENGINE_ROOT = resolve(process.cwd());
const SRC = join(ENGINE_ROOT, "src");
const OUT = join(SRC, "raw-assets", "index.ts");

const entries = new Map<string, string>();
const callExpr = /\brawAsset\(\s*["']([^"']+)["']\s*\)/g;

function walk(dir: string): string[] {
  const { readdirSync, statSync } = require("node:fs");
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

for (const file of walk(SRC)) {
  if (!file.endsWith(".ts")) continue;
  const text = readFileSync(file, "utf8");
  for (const match of text.matchAll(callExpr)) {
    const [, spec] = match;
    const key = spec.replaceAll("\\", "/");
    if (entries.has(key)) continue;
    const resolved = join(ENGINE_ROOT, key);
    if (!existsSync(resolved)) {
      console.warn(`skip missing raw asset: ${key} (used by ${relative(process.cwd(), file)})`);
      continue;
    }
    entries.set(key, readFileSync(resolved, "utf8"));
  }
}

const body = [...entries.entries()]
  .map(([key, content]) => `  ${JSON.stringify(key)}: ${JSON.stringify(content)},`)
  .join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-raw-assets.ts — do not hand-edit.\n// Run \`bun scripts/generate-raw-assets.ts\` after changing skill/guide assets.\nexport const rawAssets: Record<string, string> = {\n${body}\n};\n\nexport function rawAsset(key: string): string {\n  const value = rawAssets[key];\n  if (value === undefined) {\n    throw new Error(\`Missing raw asset: \${key}\`);\n  }\n  return value;\n}\n`,
);
console.log(`generated ${entries.size} raw assets -> ${OUT}`);
