export const MAX_CHAT_TURNS_IN_CONTEXT = 3;
export const DEFAULT_MAX_TOOL_CALL_STEPS = 40;
export const TRIVIAL_MAX_TOOL_CALL_STEPS = 15;
export const SINGLE_SCREEN_MAX_TOOL_CALL_STEPS = 30;
export const MULTI_SCREEN_MAX_TOOL_CALL_STEPS = 60;
export const MAX_TOOL_CALL_STEPS_CEILING = 100;
